version: '3.8'

services:
  web:
    build:
      context: .
    restart: unless-stopped
    ports:
      - $WEB_PORT:$WEB_PORT
    depends_on:
      - postgresdb
    environment:
      - WEB_PORT=$WEB_PORT
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DBNAME=$POSTGRES_DBNAME
      - POSTGRES_PORT=$POSTGRES_PORT

  postgresDb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DBNAME
      - POSTGRES_PORT=$POSTGRES_PORT
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql

  pgAdmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgresdb
    ports:
      - $PGADMIN_PORT:80
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_USER
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
    volumes:
      - ./postgres/pgAdmin:/var/lib/pgadmin