version: '3.8'

services:
  web:
    container_name: byteling.web.prod
    build:
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=prod
    command: sh -c "npm run build && npm run node"

  postgresDb:
    container_name: byteling.postgresDb.prod
  
  pgAdmin:
    container_name: byteling.pgAdmin.prod