version: '3.8'

services:
  web:
    container_name: byteling.web.dev.local
    build:
      dockerfile: Dockerfile.dev.local
    environment:
      - NODE_ENV=dev.local
    volumes:
      - .:/usr/src/app
    command: npm run nodemon
  
  postgresDb:
    container_name: byteling.postgresDb.dev.local
  
  pgAdmin:
    container_name: byteling.pgAdmin.dev.local