name: Dev Deployment

on:
  push:
    branches:
      - 'dev'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Run ssh command!!!
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            cd byteling.dev
            git pull
            docker compose -f docker-compose.yml -f docker-compose.dev.remote.yml build web
            docker compose -f docker-compose.yml -f docker-compose.dev.remote.yml down web
            docker compose -f docker-compose.yml -f docker-compose.dev.remote.yml up -d web
            docker builder prune -f