name: Prod Deployment

on:
  push:
    branches:
      - 'main'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Run ssh command!!!
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            cd salzachweb.prod
            git pull
            docker compose -f docker-compose.yml -f docker-compose.prod.yml build web
            docker compose -f docker-compose.yml -f docker-compose.prod.yml down web
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d web